// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/custom_blueprint.dart';
import 'models/event.dart';
import 'models/pet.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8546734659797527963),
    name: 'CustomBlueprint',
    lastPropertyId: const obx_int.IdUid(5, 4142549855465148341),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4333827610886113959),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2044255750406655882),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3115883051757122105),
        name: 'iconKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5261524512137719074),
        name: 'componentsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4142549855465148341),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8717232149059686062),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8820263826703386721),
    name: 'Event',
    lastPropertyId: const obx_int.IdUid(7, 8029470192288344454),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7622503497045443430),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2597696711005218829),
        name: 'systemComponents',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5076695756862224177),
        name: 'customBlueprintIds',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3476470156531944469),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3828954674295552334),
        name: 'loggedByName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4991719310719718558),
        name: 'displayLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8029470192288344454),
        name: 'petId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3339728177711621090),
        relationField: 'pet',
        relationTarget: 'Pet',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8219450444880363251),
    name: 'Pet',
    lastPropertyId: const obx_int.IdUid(6, 138080098963188996),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7427169430660904586),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5674744947463350052),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4388514100910832019),
        name: 'species',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4373806791044987885),
        name: 'breed',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2659906705516616603),
        name: 'birthdate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 138080098963188996),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'events',
        srcEntity: 'Event',
        srcField: 'pet',
      ),
      obx_int.ModelBacklink(
        name: 'customBlueprints',
        srcEntity: 'CustomBlueprint',
        srcField: 'pet',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8219450444880363251),
    lastIndexId: const obx_int.IdUid(2, 3339728177711621090),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CustomBlueprint: obx_int.EntityDefinition<CustomBlueprint>(
      model: _entities[0],
      toOneRelations: (CustomBlueprint object) => [object.pet],
      toManyRelations: (CustomBlueprint object) => {},
      getId: (CustomBlueprint object) => object.id,
      setId: (CustomBlueprint object, int id) {
        object.id = id;
      },
      objectToFB: (CustomBlueprint object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconKeyOffset = object.iconKey == null
            ? null
            : fbb.writeString(object.iconKey!);
        final componentsJsonOffset = fbb.writeString(object.componentsJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconKeyOffset);
        fbb.addOffset(3, componentsJsonOffset);
        fbb.addInt64(4, object.pet.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final iconKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final componentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = CustomBlueprint(
          name: nameParam,
          iconKey: iconKeyParam,
          componentsJson: componentsJsonParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
    Event: obx_int.EntityDefinition<Event>(
      model: _entities[1],
      toOneRelations: (Event object) => [object.pet],
      toManyRelations: (Event object) => {},
      getId: (Event object) => object.id,
      setId: (Event object, int id) {
        object.id = id;
      },
      objectToFB: (Event object, fb.Builder fbb) {
        final systemComponentsOffset = fbb.writeList(
          object.systemComponents.map(fbb.writeString).toList(growable: false),
        );
        final customBlueprintIdsOffset = fbb.writeListInt64(
          object.customBlueprintIds,
        );
        final loggedByNameOffset = fbb.writeString(object.loggedByName);
        final displayLabelOffset = fbb.writeString(object.displayLabel);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, systemComponentsOffset);
        fbb.addOffset(2, customBlueprintIdsOffset);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, loggedByNameOffset);
        fbb.addOffset(5, displayLabelOffset);
        fbb.addInt64(6, object.pet.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final systemComponentsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 6, []);
        final customBlueprintIdsParam = const fb.ListReader<int>(
          fb.Int64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final loggedByNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final displayLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Event(
          systemComponents: systemComponentsParam,
          customBlueprintIds: customBlueprintIdsParam,
          timestamp: timestampParam,
          loggedByName: loggedByNameParam,
          displayLabel: displayLabelParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.pet.attach(store);
        return object;
      },
    ),
    Pet: obx_int.EntityDefinition<Pet>(
      model: _entities[2],
      toOneRelations: (Pet object) => [],
      toManyRelations: (Pet object) => {
        obx_int.RelInfo<Event>.toOneBacklink(
          7,
          object.id,
          (Event srcObject) => srcObject.pet,
        ): object.events,
        obx_int.RelInfo<CustomBlueprint>.toOneBacklink(
          5,
          object.id,
          (CustomBlueprint srcObject) => srcObject.pet,
        ): object.customBlueprints,
      },
      getId: (Pet object) => object.id,
      setId: (Pet object, int id) {
        object.id = id;
      },
      objectToFB: (Pet object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final speciesOffset = object.species == null
            ? null
            : fbb.writeString(object.species!);
        final breedOffset = object.breed == null
            ? null
            : fbb.writeString(object.breed!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, speciesOffset);
        fbb.addOffset(3, breedOffset);
        fbb.addInt64(4, object.birthdate?.millisecondsSinceEpoch);
        fbb.addOffset(5, photoPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final birthdateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final speciesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final breedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final birthdateParam = birthdateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(birthdateValue);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = Pet(
          name: nameParam,
          species: speciesParam,
          breed: breedParam,
          birthdate: birthdateParam,
          photoPath: photoPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<Pet>(
          object.events,
          store,
          obx_int.RelInfo<Event>.toOneBacklink(
            7,
            object.id,
            (Event srcObject) => srcObject.pet,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Pet>(
          object.customBlueprints,
          store,
          obx_int.RelInfo<CustomBlueprint>.toOneBacklink(
            5,
            object.id,
            (CustomBlueprint srcObject) => srcObject.pet,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CustomBlueprint] entity fields to define ObjectBox queries.
class CustomBlueprint_ {
  /// See [CustomBlueprint.id].
  static final id = obx.QueryIntegerProperty<CustomBlueprint>(
    _entities[0].properties[0],
  );

  /// See [CustomBlueprint.name].
  static final name = obx.QueryStringProperty<CustomBlueprint>(
    _entities[0].properties[1],
  );

  /// See [CustomBlueprint.iconKey].
  static final iconKey = obx.QueryStringProperty<CustomBlueprint>(
    _entities[0].properties[2],
  );

  /// See [CustomBlueprint.componentsJson].
  static final componentsJson = obx.QueryStringProperty<CustomBlueprint>(
    _entities[0].properties[3],
  );

  /// See [CustomBlueprint.pet].
  static final pet = obx.QueryRelationToOne<CustomBlueprint, Pet>(
    _entities[0].properties[4],
  );
}

/// [Event] entity fields to define ObjectBox queries.
class Event_ {
  /// See [Event.id].
  static final id = obx.QueryIntegerProperty<Event>(_entities[1].properties[0]);

  /// See [Event.systemComponents].
  static final systemComponents = obx.QueryStringVectorProperty<Event>(
    _entities[1].properties[1],
  );

  /// See [Event.customBlueprintIds].
  static final customBlueprintIds = obx.QueryIntegerVectorProperty<Event>(
    _entities[1].properties[2],
  );

  /// See [Event.timestamp].
  static final timestamp = obx.QueryDateProperty<Event>(
    _entities[1].properties[3],
  );

  /// See [Event.loggedByName].
  static final loggedByName = obx.QueryStringProperty<Event>(
    _entities[1].properties[4],
  );

  /// See [Event.displayLabel].
  static final displayLabel = obx.QueryStringProperty<Event>(
    _entities[1].properties[5],
  );

  /// See [Event.pet].
  static final pet = obx.QueryRelationToOne<Event, Pet>(
    _entities[1].properties[6],
  );
}

/// [Pet] entity fields to define ObjectBox queries.
class Pet_ {
  /// See [Pet.id].
  static final id = obx.QueryIntegerProperty<Pet>(_entities[2].properties[0]);

  /// See [Pet.name].
  static final name = obx.QueryStringProperty<Pet>(_entities[2].properties[1]);

  /// See [Pet.species].
  static final species = obx.QueryStringProperty<Pet>(
    _entities[2].properties[2],
  );

  /// See [Pet.breed].
  static final breed = obx.QueryStringProperty<Pet>(_entities[2].properties[3]);

  /// See [Pet.birthdate].
  static final birthdate = obx.QueryDateProperty<Pet>(
    _entities[2].properties[4],
  );

  /// See [Pet.photoPath].
  static final photoPath = obx.QueryStringProperty<Pet>(
    _entities[2].properties[5],
  );

  /// see [Pet.events]
  static final events = obx.QueryBacklinkToMany<Event, Pet>(Event_.pet);

  /// see [Pet.customBlueprints]
  static final customBlueprints = obx.QueryBacklinkToMany<CustomBlueprint, Pet>(
    CustomBlueprint_.pet,
  );
}
